declare module "lucide-react" {
  import { FC, SVGProps } from "react";
  export type Icon = FC<SVGProps<SVGSVGElement> & { size?: number | string }>;
  export const Activity: Icon;
  export const AlertCircle: Icon;
  export const AlertTriangle: Icon;
  export const ArrowLeft: Icon;
  export const ArrowRight: Icon;
  export const ArrowUpRight: Icon;
  export const BarChart: Icon;
  export const BarChart3: Icon;
  export const Bell: Icon;
  export const BellOff: Icon;
  export const BookOpen: Icon;
  export const Bot: Icon;
  export const Check: Icon;
  export const CheckCircle: Icon;
  export const CheckCircle2: Icon;
  export const ChevronDown: Icon;
  export const ChevronLeft: Icon;
  export const ChevronRight: Icon;
  export const ChevronUp: Icon;
  export const ChevronsUpDown: Icon;
  export const Clock: Icon;
  export const Code: Icon;
  export const Code2: Icon;
  export const Copy: Icon;
  export const CreditCard: Icon;
  export const Download: Icon;
  export const Edit: Icon;
  export const ExternalLink: Icon;
  export const Eye: Icon;
  export const EyeOff: Icon;
  export const Filter: Icon;
  export const Globe: Icon;
  export const Hash: Icon;
  export const HelpCircle: Icon;
  export const Home: Icon;
  export const Image: Icon;
  export const Info: Icon;
  export const Key: Icon;
  export const KeyRound: Icon;
  export const Layers: Icon;
  export const LayoutDashboard: Icon;
  export const Link: Icon;
  export const Loader2: Icon;
  export const Lock: Icon;
  export const LogIn: Icon;
  export const LogOut: Icon;
  export const Mail: Icon;
  export const Menu: Icon;
  export const MessageCircle: Icon;
  export const MessageSquare: Icon;
  export const Minus: Icon;
  export const Monitor: Icon;
  export const Moon: Icon;
  export const MoreHorizontal: Icon;
  export const MousePointerClick: Icon;
  export const Pause: Icon;
  export const Play: Icon;
  export const Plus: Icon;
  export const RefreshCw: Icon;
  export const ScrollText: Icon;
  export const Search: Icon;
  export const Send: Icon;
  export const Settings: Icon;
  export const Share2: Icon;
  export const Shield: Icon;
  export const ShoppingBag: Icon;
  export const ShoppingCart: Icon;
  export const SlidersHorizontal: Icon;
  export const Smartphone: Icon;
  export const Sparkles: Icon;
  export const Sun: Icon;
  export const Target: Icon;
  export const Terminal: Icon;
  export const Trash2: Icon;
  export const TrendingUp: Icon;
  export const TrendingDown: Icon;
  export const Tv: Icon;
  export const Tv2: Icon;
  export const Users: Icon;
  export const UserPlus: Icon;
  export const UserCheck: Icon;
  export const UserX: Icon;
  export const UserMinus: Icon;
  export const X: Icon;
  export const XCircle: Icon;
  export const Zap: Icon;
  export const ZapOff: Icon;
  export const AlertOctagon: Icon;
  export const AlignLeft: Icon;
  export const Archive: Icon;
  export const Award: Icon;
  export const Bookmark: Icon;
  export const Braces: Icon;
  export const Briefcase: Icon;
  export const Calendar: Icon;
  export const Camera: Icon;
  export const ChartBar: Icon;
  export const ChartBarBig: Icon;
  export const ChartBarStacked: Icon;
  export const Clipboard: Icon;
  export const Coffee: Icon;
  export const Columns: Icon;
  export const Compass: Icon;
  export const Cpu: Icon;
  export const Database: Icon;
  export const Disc: Icon;
  export const DollarSign: Icon;
  export const Droplets: Icon;
  export const FastForward: Icon;
  export const Feather: Icon;
  export const FileText: Icon;
  export const Flag: Icon;
  export const Flame: Icon;
  export const Folder: Icon;
  export const Gift: Icon;
  export const GitBranch: Icon;
  export const Github: Icon;
  export const GlobeIcon: Icon;
  export const Grid: Icon;
  export const Grip: Icon;
  export const Hammer: Icon;
  export const Heart: Icon;
  export const Inbox: Icon;
  export const Instagram: Icon;
  export const LifeBuoy: Icon;
  export const Lightbulb: Icon;
  export const Linkedin: Icon;
  export const List: Icon;
  export const Loader: Icon;
  export const MapPin: Icon;
  export const Megaphone: Icon;
  export const Mic: Icon;
  export const Minimize2: Icon;
  export const MonitorDown: Icon;
  export const MoonStar: Icon;
  export const Music: Icon;
  export const Navigation: Icon;
  export const Package: Icon;
  export const Paperclip: Icon;
  export const Pencil: Icon;
  export const Percent: Icon;
  export const Phone: Icon;
  export const PieChart: Icon;
  export const Pin: Icon;
  export const Pointer: Icon;
  export const Power: Icon;
  export const Radio: Icon;
  export const Repeat: Icon;
  export const Reply: Icon;
  export const Rocket: Icon;
  export const Rss: Icon;
  export const Save: Icon;
  export const Scissors: Icon;
  export const ScreenShare: Icon;
  export const Server: Icon;
  export const Share: Icon;
  export const ShieldAlert: Icon;
  export const ShieldCheck: Icon;
  export const Shuffle: Icon;
  export const Sidebar: Icon;
  export const Sigma: Icon;
  export const Siren: Icon;
  export const SkipBack: Icon;
  export const SkipForward: Icon;
  export const Slash: Icon;
  export const Sliders: Icon;
  export const SmartphoneNfc: Icon;
  export const Speaker: Icon;
  export const Square: Icon;
  export const Star: Icon;
  export const StopCircle: Icon;
  export const SunMoon: Icon;
  export const SwatchBook: Icon;
  export const Table: Icon;
  export const Tag: Icon;
  export const TestTube: Icon;
  export const ThumbsUp: Icon;
  export const Timer: Icon;
  export const ToggleLeft: Icon;
  export const ToggleRight: Icon;
  export const Tool: Icon;
  export const Upload: Icon;
  export const User: Icon;
  export const Wallet: Icon;
  export const Wand2: Icon;
  export const Watch: Icon;
  export const Waves: Icon;
  export const Webhook: Icon;
  export const Wifi: Icon;
  export const Wind: Icon;
  export const Youtube: Icon;
  export const ZoomIn: Icon;
  export const ZoomOut: Icon;
  export const Lightbulb: Icon;
  export const List: Icon;
  export const RefreshCcw: Icon;
  export const CalendarClock: Icon;
  export const Settings2: Icon;
  export const FileEdit: Icon;
  export const TicketCheck: Icon;
  export const Ban: Icon;
  export const PenLine: Icon;
  export const RotateCw: Icon;
  export const Workflow: Icon;
  export const Split: Icon;
  export const MoreVertical: Icon;
  export const Blocks: Icon;
  export const Building2: Icon;
  export const GitFork: Icon;
  export const GripVertical: Icon;
  export const Puzzle: Icon;
  export const UserCircle: Icon;
  export const LucideIcon: Icon;
  export const ArrowUpDown: Icon;
  export const ArrowUp: Icon;
  export const ArrowDown: Icon;
}

declare module "firebase/auth" {
  import { Auth, UserCredential, ActionCodeSettings, User } from "firebase/auth";
  export function getAuth(app?: any): Auth;
  export function signInWithEmailAndPassword(auth: Auth, email: string, password: string): Promise<UserCredential>;
  export function createUserWithEmailAndPassword(auth: Auth, email: string, password: string): Promise<UserCredential>;
  export function signInWithPopup(auth: Auth, provider: any): Promise<UserCredential>;
  export function signOut(auth: Auth): Promise<void>;
  export function onAuthStateChanged(auth: Auth, nextOrObserver: any): any;
  export function sendPasswordResetEmail(auth: Auth, email: string, actionCodeSettings?: ActionCodeSettings): Promise<void>;
  export function sendEmailVerification(user: any, actionCodeSettings?: ActionCodeSettings): Promise<void>;
  export function updateProfile(user: any, profile: { displayName?: string; photoURL?: string }): Promise<void>;
  export function applyActionCode(auth: Auth, oobCode: string): Promise<void>;
  export function checkActionCode(auth: Auth, oobCode: string): Promise<any>;
  export function verifyPasswordResetCode(auth: Auth, oobCode: string): Promise<string>;
  export function confirmPasswordReset(auth: Auth, oobCode: string, newPassword: string): Promise<void>;
  export class GoogleAuthProvider {
    static PROVIDER_ID: string;
    constructor();
    addScope(scope: string): void;
    setCustomParameters(params: Record<string, string>): void;
  }
  export class GithubAuthProvider {
    static PROVIDER_ID: string;
    constructor();
    addScope(scope: string): void;
    setCustomParameters(params: Record<string, string>): void;
  }
  export type ActionCodeSettings = any;
  export type User = any;
}

declare module "firebase/app" {
  import { FirebaseApp, FirebaseOptions } from "firebase/app";
  export function initializeApp(options: FirebaseOptions, name?: string): FirebaseApp;
  export function getApp(name?: string): FirebaseApp;
  export type FirebaseOptions = Record<string, any>;
}

declare module "firebase/messaging" {
  import { Messaging } from "firebase/messaging";
  export function getMessaging(app?: any): Messaging;
  export function getToken(messaging: Messaging, options?: any): Promise<string>;
  export function onMessage(messaging: Messaging, nextOrObserver: any): any;
}